### ISSUE TITLE
remove_menu_pages does not remove edit_comments.php correctly

### ISSUE THREAD

**Issue by villepietarinen** [devgeniem/wp-geniem-roles#19]
The page is removed from the left side navigation but is still accessible from top bar if site is multisite

**Comment by Liblastic** [comment]
Nicely noticed!
We should remove it from the $wp_admin_bar global as well.

global $wp_admin_bar;
$wp_admin_bar->remove_menu( 'comments' );

**Comment by Liblastic** [comment]
This has been fixed after release 1.0.2
