### ISSUE TITLE
Adding multiple caps for default WordPress roles with wp-geniem-roles $admin->add_caps() not working

### ISSUE THREAD

**Issue by Liblastic** [devgeniem/wp-geniem-roles#29]
Only the first cap will be added.

**Comment by Liblastic** [comment]
Branch `addcaps-hotfix` will fix the problem.
https://github.com/devgeniem/wp-geniem-roles/tree/addcaps-hotfix

**Comment by ivuorinen** [comment]
Closing this as https://github.com/devgeniem/wp-geniem-roles/pull/30 was accepted, merged and released. See version [1.2.2](https://github.com/devgeniem/wp-geniem-roles/releases/tag/1.2.2).
